"""create delivery orders

Revision ID: 1ad8c93f8cfe
Revises: 7b3f536e913b
Create Date: 2026-07-15 00:56:21.917969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad8c93f8cfe'
down_revision: Union[str, Sequence[str], None] = '9d18dadd67a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('order_type', sa.Enum('DELIVERY', 'PICKUP', name='ordertype'), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('payment_method', sa.Enum('CASH', 'QR', name='paymentmethod'), nullable=True),
    sa.Column('change_from', sa.String(), nullable=True),
    sa.Column('delivery_time', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'ACCEPTED', 'COOKING', 'READY', 'DELIVERING', 'DONE', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
